# 01. Data Loading

## Цель
Загрузить dataset, проверить его структуру, определить целевую переменную, выделить признаки для дальнейшего EDA и построения модели классификации бухгалтерских документов.

In [1]:
import pandas as pd
import numpy as np

In [3]:
activities_data_df = pd.read_excel("../data/activities_data.xlsx")
activities_data_df.head()

,Activity_Code,Activity_Description
0,3250706,Dental prosthesis services
1,3250709,Optical laboratory services
2,4399101,Construction management
3,4512901,Commercial representatives and agents of motor vehicle trade
4,4530702,Wholesale trade of tires and inner tubes

In [4]:
invoices_classification_df = pd.read_excel("../data/invoices_classification.xlsx")
invoices_classification_df

,Dataset,Date,Invoice,Supplier_Code,Supplier_Name,Invoice_Item,Item_Description,Item_Value,Item_Quantity,Total_Amount,Taxes_Credit_%,Taxes_Credit_Amount,Total_Net_Amount,Account_Number,Account_Description
0,Training,2019-08-15,91,10001,ABS & ABC Tax Consulting,1,Review of federal tax obligations,2000,1,2000,0,0.0,2000.0,4000010,Audit and Consulting
1,Training,2019-08-15,186,10002,HJU Travel Agency,1,Assistance with flight and hotel arrangements,500,1,500,0,0.0,500.0,4000080,Other Third-Party Services
2,Training,2019-08-15,275,10003,ABC Associated Lawyers,1,Legal advisory in labor lawsuit,2000,1,2000,0,0.0,2000.0,4000012,Legal Services
3,Training,2019-08-15,135,10004,ATY Business Consulting,1,Consulting on zero-based budgeting,15000,1,15000,0,0.0,15000.0,4000010,Audit and Consulting
4,Training,2019-08-15,221,10005,HBG Security and Surveillance,1,Provision of 2 security guards for gate,15000,1,15000,0,0.0,15000.0,4000015,Security and Surveillance
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,Test,2024-01-01,650,10023,MHG Industrial Tools,2,Tool ASR,4300,1,4300,20,860.0,3440.0,1001004,Industrial Tools
339,Test,2024-01-01,189,10024,PKM Quality Systems Auditing,1,ISO 9001 audit,25000,1,25000,0,0.0,25000.0,5000010,Audit and Consulting
340,Test,2024-01-01,511,10025,PLM Industrial Hardware,1,Reinforced belt,260,2,520,20,104.0,416.0,5000034,Industrial Tools
341,Test,2024-01-01,685,10026,PRP Corporate Benefits,1,Meal voucher purchase,24000,1,24000,0,0.0,24000.0,5000003,Meal Voucher
342,Test,2024-01-01,455,10027,QTR Safety Training,1,Safety simulations,2500,1,2500,0,0.0,2500.0,5000028,Training

In [5]:
suppliers_data_df = pd.read_excel("../data/suppliers_data.xlsx")
suppliers_data_df

,Supplier_Code,Supplier_Name,Activity_Code,Activity_Description
0,10001,ABS & ABC Tax Consulting,7020400,"Business management consulting, except specialized technical consulting"
1,10002,HJU Travel Agency,7911200,Travel agencies
2,10003,ABC Associated Lawyers,6911701,Legal services
3,10004,ATY Business Consulting,7020400,"Business management consulting, except specialized technical consulting"
4,10005,HBG Security and Surveillance,8020001,Electronic security system monitoring activities
5,10006,BGT Electrical Materials Trading,4742300,Retail trade of electrical materials
6,10007,CBJ Corporate Training,8599604,Professional and managerial development training
7,10008,CSF Wholesale and Retail,4744001,Retail trade of hardware and tools
8,10009,KLZ Payment Solutions,6204000,IT consulting
9,10010,BBT Cleaning Services,8121400,Building and residential cleaning
10,10011,MFR Cleaning Supplies,4789005,Retail trade of household cleaning products
11,10012,CBX Auditing and Consulting,6621502,Actuarial auditing and consulting
12,10013,CBZ Recruitment Advisory,7020400,"Business management consulting, except specialized technical consulting"
13,10014,MHG Industrial Tools,4744001,Retail trade of hardware and tools
14,10015,PKM Quality Systems Auditing,7020400,"Business management consulting, except specialized technical consulting"
15,10016,WER Real Estate Services,6822600,Real estate property management and administration
16,10017,YFC Textile Products,4755501,Retail trade of fabrics
17,10018,PLM Industrial Hardware,4613300,"Commercial representatives and agents of wood, construction materials, and hardware"
18,10019,TRQ Advertising Consulting,7319004,Advertising consulting
19,10020,XRO Marketing Agency,7311400,Advertising agencies
20,10021,PRP Corporate Benefits,8299799,Other business support services not elsewhere classified
21,10022,WRL PPE Trading,4789099,Retail trade of other products not elsewhere classified
22,10023,YTR Chemical Industry,4612500,"Commercial representatives and agents of fuels, minerals, steel, and chemical products"
23,10024,SAZ Industrial Machinery,4614100,"Commercial representatives and agents of machinery, equipment, ships, and aircraft"
24,10025,QBZ DataTech,6204000,IT consulting
25,10026,QTR Safety Training,7119704,Technical expertise services related to occupational safety
26,10027,QGF Human Resources Solutions,8299799,Other business support services not elsewhere classified

In [6]:
dfs = {
    "activities_data": activities_data_df,
    "invoices_classification": invoices_classification_df,
    "suppliers_data": suppliers_data_df
}

for name, df in dfs.items():
    print("=" * 80)
    print(f"{name}")
    print(f"shape: {df.shape}")
    print("\ncolumns:")
    print(df.columns.tolist())
    print("\ndtypes:")
    print(df.dtypes)
    print("\nmissing values:")
    print(df.isna().sum().sort_values(ascending=False).head(20))
    print("\nhead:")
    display(df.head(3))

================================================================================
activities_data
shape: (391, 2)

columns:
['Activity_Code', 'Activity_Description']

dtypes:
Activity_Code           int64
Activity_Description      str
dtype: object

missing values:
Activity_Code           0
Activity_Description    0
dtype: int64

head:

   Activity_Code           Activity_Description
0        3250706   Dental prosthesis services
1        3250709  Optical laboratory services
2        4399101      Construction management

================================================================================
invoices_classification
shape: (343, 15)

columns:
['Dataset', 'Date', 'Invoice', 'Supplier_Code', 'Supplier_Name', 'Invoice_Item', 'Item_Description', 'Item_Value', 'Item_Quantity', 'Total_Amount', 'Taxes_Credit_%', 'Taxes_Credit_Amount', 'Total_Net_Amount', 'Account_Number', 'Account_Description']

dtypes:
Dataset                           str
Date                   datetime64[us]
Invoice                         int64
Supplier_Code                   int64
Supplier_Name                     str
Invoice_Item                    int64
Item_Description                  str
Item_Value                      int64
Item_Quantity                   int64
Total_Amount                    int64
Taxes_Credit_%                  int64
Taxes_Credit_Amount           float64
Total_Net_Amount              float64
Account_Number                  int64
Account_Description               str
dtype: object

missing values:
Dataset                0
Date                   0
Invoice                0
Supplier_Code          0
Supplier_Name          0
Invoice_Item           0
Item_Description       0
Item_Value             0
Item_Quantity          0
Total_Amount           0
Taxes_Credit_%         0
Taxes_Credit_Amount    0
Total_Net_Amount       0
Account_Number         0
Account_Description    0
dtype: int64

head:

,Dataset,Date,Invoice,Supplier_Code,Supplier_Name,Invoice_Item,Item_Description,Item_Value,Item_Quantity,Total_Amount,Taxes_Credit_%,Taxes_Credit_Amount,Total_Net_Amount,Account_Number,Account_Description
0,Training,2019-08-15,91,10001,ABS & ABC Tax Consulting,1,Review of federal tax obligations,2000,1,2000,0,0.0,2000.0,4000010,Audit and Consulting
1,Training,2019-08-15,186,10002,HJU Travel Agency,1,Assistance with flight and hotel arrangements,500,1,500,0,0.0,500.0,4000080,Other Third-Party Services
2,Training,2019-08-15,275,10003,ABC Associated Lawyers,1,Legal advisory in labor lawsuit,2000,1,2000,0,0.0,2000.0,4000012,Legal Services

================================================================================
suppliers_data
shape: (27, 4)

columns:
['Supplier_Code', 'Supplier_Name', 'Activity_Code', 'Activity_Description']

dtypes:
Supplier_Code           int64
Supplier_Name             str
Activity_Code           int64
Activity_Description      str
dtype: object

missing values:
Supplier_Code           0
Supplier_Name           0
Activity_Code           0
Activity_Description    0
dtype: int64

head:

,Supplier_Code,Supplier_Name,Activity_Code,Activity_Description
0,10001,ABS & ABC Tax Consulting,7020400,"Business management consulting, except specialized technical consulting"
1,10002,HJU Travel Agency,7911200,Travel agencies
2,10003,ABC Associated Lawyers,6911701,Legal services

In [7]:
for name, df in dfs.items():
    print("=" * 80)
    print(name)
    nunique_df = pd.DataFrame({
        "column": df.columns,
        "nunique": [df[col].nunique(dropna=False) for col in df.columns],
        "dtype": [df[col].dtype for col in df.columns]
    }).sort_values("nunique")
    display(nunique_df)

================================================================================
activities_data

                 column  nunique  dtype
0         Activity_Code      391  int64
1  Activity_Description      391    str

================================================================================
invoices_classification

                 column  nunique           dtype
0               Dataset        2             str
10       Taxes_Credit_%        3           int64
5          Invoice_Item        6           int64
14  Account_Description       20             str
8         Item_Quantity       25           int64
13       Account_Number       27           int64
3         Supplier_Code       27           int64
4         Supplier_Name       28             str
11  Taxes_Credit_Amount       46         float64
1                  Date       53  datetime64[us]
7            Item_Value       79           int64
9          Total_Amount       85           int64
12     Total_Net_Amount      100         float64
6      Item_Description      123             str
2               Invoice      303           int64

================================================================================
suppliers_data

                 column  nunique  dtype
3  Activity_Description       21    str
2         Activity_Code       21  int64
1         Supplier_Name       27    str
0         Supplier_Code       27  int64

In [8]:
for name, df in dfs.items():
    print("=" * 80)
    print(name)
    
    obj_cols = df.select_dtypes(include=["object"]).columns
    
    for col in obj_cols:
        nunique = df[col].nunique(dropna=False)
        if nunique <= 20:
            print(f"\n--- {col} ({nunique} unique) ---")
            print(df[col].value_counts(dropna=False).head(20))

================================================================================
activities_data
================================================================================
invoices_classification

--- Dataset (2 unique) ---
Dataset
Training    292
Test         51
Name: count, dtype: int64

--- Account_Description (20 unique) ---
Account_Description
Audit and Consulting                   54
Building Rentals                       50
Security and Surveillance              35
Raw Material                           26
Other Third-Party Services             25
Advertising and Marketing              22
Cleaning Services                      20
Uniforms                               18
Personal Protective Equipment (PPE)    15
Industrial Tools                       13
Training                               12
Consumables                            12
Legal Services                         10
Information Technology                  7
Cleaning Products                       6
Building Maintenance                    5
Recruitment and Selection               4
Meal Voucher                            4
Equipment Maintenance                   3
Machinery and Equipment                 2
Name: count, dtype: int64
================================================================================
suppliers_data

C:\Users\Artyom Ugreninov\AppData\Local\Temp\ipykernel_12068\354577128.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = df.select_dtypes(include=["object"]).columns
C:\Users\Artyom Ugreninov\AppData\Local\Temp\ipykernel_12068\354577128.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = df.select_dtypes(include=["object"]).columns
C:\Users\Artyom Ugreninov\AppData\Local\Temp\ipykernel_12068\354577128.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = df.select_dtypes(include=["object"]).columns

In [9]:
for name, df in dfs.items():
    print(name, "->", df.columns.tolist())

activities_data -> ['Activity_Code', 'Activity_Description']
invoices_classification -> ['Dataset', 'Date', 'Invoice', 'Supplier_Code', 'Supplier_Name', 'Invoice_Item', 'Item_Description', 'Item_Value', 'Item_Quantity', 'Total_Amount', 'Taxes_Credit_%', 'Taxes_Credit_Amount', 'Total_Net_Amount', 'Account_Number', 'Account_Description']
suppliers_data -> ['Supplier_Code', 'Supplier_Name', 'Activity_Code', 'Activity_Description']

In [10]:
merged_df = invoices_classification_df.merge(
    suppliers_data_df[["Supplier_Code", "Activity_Code", "Activity_Description"]],
    on="Supplier_Code",
    how="left"
)
merged_df.head()

,Dataset,Date,Invoice,Supplier_Code,Supplier_Name,Invoice_Item,Item_Description,Item_Value,Item_Quantity,Total_Amount,Taxes_Credit_%,Taxes_Credit_Amount,Total_Net_Amount,Account_Number,Account_Description,Activity_Code,Activity_Description
0,Training,2019-08-15,91,10001,ABS & ABC Tax Consulting,1,Review of federal tax obligations,2000,1,2000,0,0.0,2000.0,4000010,Audit and Consulting,7020400,"Business management consulting, except specialized technical consulting"
1,Training,2019-08-15,186,10002,HJU Travel Agency,1,Assistance with flight and hotel arrangements,500,1,500,0,0.0,500.0,4000080,Other Third-Party Services,7911200,Travel agencies
2,Training,2019-08-15,275,10003,ABC Associated Lawyers,1,Legal advisory in labor lawsuit,2000,1,2000,0,0.0,2000.0,4000012,Legal Services,6911701,Legal services
3,Training,2019-08-15,135,10004,ATY Business Consulting,1,Consulting on zero-based budgeting,15000,1,15000,0,0.0,15000.0,4000010,Audit and Consulting,7020400,"Business management consulting, except specialized technical consulting"
4,Training,2019-08-15,221,10005,HBG Security and Surveillance,1,Provision of 2 security guards for gate,15000,1,15000,0,0.0,15000.0,4000015,Security and Surveillance,8020001,Electronic security system monitoring activities

In [11]:
print("Shape after merge:", merged_df.shape)
print("\nMissing after merge:")
print(merged_df[["Supplier_Code", "Activity_Code", "Activity_Description"]].isna().sum())

Shape after merge: (343, 17)

Missing after merge:
Supplier_Code           0
Activity_Code           0
Activity_Description    0
dtype: int64

In [13]:
print("Количество классов:", merged_df["Account_Number"].nunique())

Количество классов: 27

In [14]:
account_map = (
    merged_df[["Account_Number", "Account_Description"]]
    .drop_duplicates()
    .sort_values("Account_Number")
)

account_map

     Account_Number                  Account_Description
5           1000001                         Raw Material
305         1000001                          Consumables
9           1001002              Machinery and Equipment
107         1001004                     Industrial Tools
21          4000006                          Consumables
0           4000010                 Audit and Consulting
2           4000012                       Legal Services
52          4000013                    Cleaning Products
4           4000015            Security and Surveillance
25          4000017            Recruitment and Selection
42          4000021                 Building Maintenance
14          4000026                             Uniforms
20          4000028                             Training
7           4000030               Information Technology
309         4000030                             Training
10          4000050            Advertising and Marketing
11          4000060                     Building Rentals
1           4000080           Other Third-Party Services
23          4000090                    Cleaning Services
29          5000003                         Meal Voucher
66          5000006                          Consumables
12          5000009  Personal Protective Equipment (PPE)
27          5000010                 Audit and Consulting
24          5000013                    Cleaning Products
56          5000017            Recruitment and Selection
40          5000024                Equipment Maintenance
30          5000028                             Training
26          5000034                     Industrial Tools
72          5000060                     Building Rentals

In [15]:
account_desc_check = (
    merged_df.groupby("Account_Number")["Account_Description"]
    .nunique()
    .sort_values(ascending=False)
)

account_desc_check

Account_Number
1000001    2
4000030    2
1001002    1
4000006    1
4000010    1
4000012    1
4000013    1
4000015    1
4000017    1
4000021    1
1001004    1
4000026    1
4000028    1
4000050    1
4000060    1
4000080    1
4000090    1
5000003    1
5000006    1
5000009    1
5000010    1
5000013    1
5000017    1
5000024    1
5000028    1
5000034    1
5000060    1
Name: Account_Description, dtype: int64

In [16]:
problem_accounts = account_desc_check[account_desc_check > 1].index.tolist()
problem_accounts

[1000001, 4000030]

In [17]:
merged_df.loc[
    merged_df["Account_Number"].isin(problem_accounts),
    ["Account_Number", "Account_Description"]
].drop_duplicates().sort_values(["Account_Number", "Account_Description"])

     Account_Number     Account_Description
305         1000001             Consumables
5           1000001            Raw Material
7           4000030  Information Technology
309         4000030                Training

## Предварительный вывод по целевой переменной

В качестве целевой переменной для задачи классификации будет использоваться `Account_Number`.

Поле `Account_Description` не является полностью консистентным: для некоторых кодов счета в датасете присутствуют разные текстовые описания. Поэтому `Account_Description` будет использоваться только для интерпретации результатов, но не как обучающая метка и не как признак модели.

In [19]:
target_counts = merged_df["Account_Number"].value_counts()
print("Количество объектов:", len(merged_df))
print("Количество классов:", merged_df["Account_Number"].nunique())
print("Минимум объектов в классе:", target_counts.min())
print("Максимум объектов в классе:", target_counts.max())
print("Медиана объектов в классе:", target_counts.median())
target_counts

Количество объектов: 343
Количество классов: 27
Минимум объектов в классе: 1
Максимум объектов в классе: 50
Медиана объектов в классе: 6.0

Account_Number
4000010    50
4000015    35
1000001    27
4000080    25
4000060    25
5000060    25
4000050    22
4000090    20
4000026    18
5000009    15
4000012    10
5000034     9
4000030     8
4000028     6
4000006     6
5000013     5
5000028     5
4000021     5
5000006     5
5000010     4
5000003     4
1001004     4
4000017     3
5000024     3
1001002     2
4000013     1
5000017     1
Name: count, dtype: int64

In [22]:
merged_df.to_csv('../data/modified/merged_dataframe.csv', index=False)

## Итоги первого этапа

В ходе загрузки и первичного анализа данных были рассмотрены три таблицы:

- `activities_data` — справочник видов деятельности;
- `suppliers_data` — таблица поставщиков с привязкой к виду деятельности;
- `invoices_classification` — основная таблица с данными по строкам счетов и бухгалтерской классификацией.

Для формирования рабочей обучающей выборки таблица `invoices_classification` была объединена с `suppliers_data` по полю `Supplier_Code`, что позволило добавить информацию о виде деятельности поставщика.

В качестве целевой переменной выбрано поле `Account_Number`, так как оно представляет собой код бухгалтерского счета. Поле `Account_Description` оказалось неконсистентным: для некоторых кодов счета присутствуют разные текстовые описания. По этой причине `Account_Description` не будет использоваться ни как целевая переменная, ни как входной признак модели.

Следующим этапом будет выполнен разведочный анализ данных (EDA) для изучения распределения классов, текстовых признаков, числовых признаков и возможных ограничений набора данных.